AspNetworkTestTool/Models/ErrorViewModel.cs
namespace AspNetworkTestTool.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetworkTestTool/Controllers/DatabaseController.cs
using Microsoft.AspNetCore.Mvc;
using Yinyang.Utilities.MySql;
using Yinyang.Utilities.Npgsql;
using Yinyang.Utilities.Oracle.Core;
using Yinyang.Utilities.SqlServer;

namespace AspNetworkTestTool.Controllers;

public class DatabaseController : Controller
{
    [HttpGet]
    public IActionResult Index()
    {
        ViewBag.DatabaseResult = "No Connect.";
        return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Index(string connectionString, string database)
    {
        if (!string.IsNullOrEmpty(connectionString) && !string.IsNullOrEmpty(database))
        {
            ViewBag.ConnectionString = connectionString;
            ViewBag.Database = database;

            switch (database)
            {
                case "postgresql":
                    try
                    {
                        var db = new Pgsql(connectionString);
                        db.Open();
                        db.Close();
                        ViewBag.DatabaseResult = "Success.";
                        ViewBag.DatabaseError = "Success.";
                    }
                    catch (Exception err)
                    {
                        ViewBag.DatabaseResult = "Failed.";
                        ViewBag.DatabaseError = err;
                    }

                    return View();
                case "sqlserver":
                    try
                    {
                        var db = new SqlServer(connectionString);
                        db.Open();
                        db.Close();
                        ViewBag.DatabaseResult = "Success.";
                        ViewBag.DatabaseError = "Success.";
                    }
                    catch (Exception err)
                    {
                        ViewBag.DatabaseResult = "Failed.";
                        ViewBag.DatabaseError = err;
                    }

                    return View();
                case "mysql":
                    try
                    {
                        var db = new MySqlConnect(connectionString);
                        db.Open();
                        db.Close();
                        ViewBag.DatabaseResult = "Success.";
                        ViewBag.DatabaseError = "Success.";
                    }
                    catch (Exception err)
                    {
                        ViewBag.DatabaseResult = "Failed.";
                        ViewBag.DatabaseError = err;
                    }
                    return View();
                case "oracle":
                    try
                    {
                        var db = new OracleDatabase(connectionString);
                        db.Open();
                        db.Close();
                        ViewBag.DatabaseResult = "Success.";
                        ViewBag.DatabaseError = "Success.";
                    }
                    catch (Exception err)
                    {
                        ViewBag.DatabaseResult = "Failed.";
                        ViewBag.DatabaseError = err;
                    }
                    return View();
                default:
                    ViewBag.DatabaseResult = "No Connect.";
                    return View();
            }
        }

        ViewBag.DatabaseResult = "No Connect.";
        return View();
    }
}

AspNetworkTestTool/Controllers/HomeController.cs
using System.Diagnostics;
using System.Reflection;
using AspNetworkTestTool.Models;
using Microsoft.AspNetCore.Mvc;

namespace AspNetworkTestTool.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger) => _logger = logger;

    [HttpGet]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }

    [HttpGet]
    public IActionResult Index()
    {
        ViewBag.Version = Assembly.GetExecutingAssembly().GetName().Version?.ToString();

        var rh = "";
        foreach (var key in Request.Headers.Keys)
        {
            Request.Headers.TryGetValue(key, out var values);
            rh += key + " : ";
            rh = values.Aggregate(rh, (current, value) => current + value + " ");
            rh += Environment.NewLine;
        }

        ViewBag.User = rh;
        return View();
    }
}

AspNetworkTestTool/Controllers/HttpController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetworkTestTool.Controllers;

public class HttpController : Controller
{
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Index(string url, string certificate)
    {
        if (!string.IsNullOrEmpty(url))
        {
            var checkResult = Uri.TryCreate(url, UriKind.Absolute, out var uriResult)
                              && (uriResult.Scheme == Uri.UriSchemeHttp || uriResult.Scheme == Uri.UriSchemeHttps);

            if (!checkResult)
            {
                ViewBag.HttpLog = "Invalid URL.";
                return View();
            }

            ViewBag.Url = url;

            var httpClientHandler = new HttpClientHandler();

            if (certificate == "on")
            {
                httpClientHandler.ServerCertificateCustomValidationCallback = delegate { return true; };
            }

            HttpClient httpClient = new(httpClientHandler);

            try
            {
                var response = httpClient.GetAsync(uriResult).Result;
                ViewBag.HttpResult = response.StatusCode;
                ViewBag.HttpLog = response.Content.ReadAsStringAsync().Result;
            }
            catch (Exception err)
            {
                ViewBag.HttpResult = "Error";
                ViewBag.HttpLog = err;
            }
        }

        return View();
    }
}

AspNetworkTestTool/Controllers/RedisController.cs
using Microsoft.AspNetCore.Mvc;
using StackExchange.Redis;

namespace AspNetworkTestTool.Controllers;

public class RedisController : Controller
{
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Index(string config)
    {
        if (!string.IsNullOrEmpty(config))
        {
            ViewBag.Config = config;

            try
            {
                var conn = ConnectionMultiplexer.Connect(config);
                conn.GetDatabase();
                conn.Close();

                ViewBag.RedisResult = "Success.";
                ViewBag.RedisLog = "Success.";
            }
            catch (Exception err)
            {
                ViewBag.RedisResult = "Error";
                ViewBag.RedisLog = err;
            }
        }

        return View();
    }
}

AspNetworkTestTool/Views/Database/Index.cshtml
@{
    ViewData["Title"] = "Database";
}
<h1>@ViewData["Title"]</h1>

<p>Please input the DB connection string to test the connection with the database.</p>

<form asp-action="Index" asp-controller="Database" method="post">
    <fieldset>
        <br/>
        <h2>ConnectionString Example</h2>
        <p>
            Oracle: Data Source=(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST =  localhost)(PORT = 1521)))(CONNECT_DATA =(SERVICE_NAME = oracle)));Persist Security Info=True;User ID=oracle;Password=oracle;<br />
            MySQL / MariaDB: Server=127.0.0.1;Database=test;User Id=root;Password=mysql;<br />
            Postgresql: Server=127.0.0.1;Port=5432;Database=postgres;User Id=postgres;Password=postgres;<br />
            SQL Server: Server=127.0.0.1;Database=test;User Id=sa;Password=sqlserver;<br/>
        </p>
        <div>
            <label for="connectionString">ConnectionString:</label>
            <input type="text" id="connectionString" name="connectionString" style="width: 100%;" value="@ViewBag.ConnectionString"/>
        </div>
        <br/>
        <div>
            <label for="database">Database:</label>
            <select id="database" name="database">
                @if (ViewBag.Database == "mysql")
                {
                    <option value="mysql" selected>MySQL / MariaDB</option>
                }
                else
                {
                    <option value="mysql">MySQL / MariaDB</option>
                }
                @if (ViewBag.Database == "oracle")
                {
                    <option value="oracle" selected>Oracle</option>
                }
                else
                {
                    <option value="oracle">Oracle</option>
                }
                @if (ViewBag.Database == "postgresql")
                {
                    <option value="postgresql" selected>Postgresql</option>
                }
                else
                {
                    <option value="postgresql">Postgresql</option>
                }
                @if (ViewBag.Database == "sqlserver")
                {
                    <option value="sqlserver" selected>SQL Server</option>
                }
                else
                {
                    <option value="sqlserver">SQL Server</option>
                }
            </select>
        </div>
        <br/>
        <div>
            <label>&nbsp;</label>
            @Html.AntiForgeryToken()
            <input type="submit" value="Test" class="submit"/>
        </div>
    </fieldset>
</form>
<hr/>
<fieldset>
    <legend>Result: @ViewBag.DatabaseResult</legend>
    <textarea readonly style="width: 100%;height: 200px;">@ViewBag.DatabaseError</textarea>
</fieldset>

AspNetworkTestTool/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <fieldset>
        <textarea readonly style="width: 100%;height: 200px;">@ViewBag.User</textarea>
    </fieldset>

    <p>Version: @ViewBag.Version</p>
</div>

AspNetworkTestTool/Views/Http/Index.cshtml
@{
    ViewData["Title"] = "HTTP";
}
<h1>@ViewData["Title"]</h1>

<p>Please enter the HTTP address.</p>

<form asp-action="Index" asp-controller="Http" method="post">
    <fieldset>
        <br />
        <div>
            <label for="url">Web Address:</label>
            <input type="text" id="url" name="url" style="width: 100%;" value="@ViewBag.Url" />
        </div>
        <br />
        <div>
            <input type="checkbox" id="certificate" name="certificate" />
            <label for="certificate">Disable server certificate verification.</label>
        </div>
        <br />
        <div>
            <label>&nbsp;</label>
            @Html.AntiForgeryToken()
            <input type="submit" value="Test" class="submit" />
        </div>
    </fieldset>
</form>
<hr />
<fieldset>
    <legend>@ViewBag.HttpResult</legend>
    <textarea readonly style="width: 100%;height: 200px;">@ViewBag.HttpLog</textarea>
</fieldset>

AspNetworkTestTool/Views/Redis/Index.cshtml
@{
    ViewData["Title"] = "Redis";
}
<h1>@ViewData["Title"]</h1>

<p>Please enter the Redis Configuration Strings.</p>

<form asp-action="Index" asp-controller="Redis" method="post">
    <fieldset>
        <br />
        <h2>Configuration Strings Example</h2>
        <p>
            localhost<br />
            redis0:6380,redis1:6380,allowAdmin=true<br />
            localhost,serviceName=myprimary<br />
        </p>
        <div>
            <label for="config">Configuration Strings:</label>
            <input type="text" id="config" name="config" style="width: 100%;" value="@ViewBag.Config" />
        </div>
        <br />
        <div>
            <label>&nbsp;</label>
            @Html.AntiForgeryToken()
            <input type="submit" value="Test" class="submit" />
        </div>
    </fieldset>
</form>
<hr />
<fieldset>
    <legend>@ViewBag.RedisResult</legend>
    <textarea readonly style="width: 100%;height: 200px;">@ViewBag.RedisLog</textarea>
</fieldset>

AspNetworkTestTool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asp DotNet TestTool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspDotNetTestTool.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestTool</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Http" asp-action="Index">Http</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Database" asp-action="Index">Database</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Redis" asp-action="Index">Redis</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a href="https://github.com/nobuo-miura/AspNetworkTestTool">GitHub</a><br/>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>